// 기본 상수 · 카드/전설 카드 데이터 · 다국어 문구
// (index.html에서 순서대로 불러오는 일반 스크립트 — 파일끼리 전역 변수·함수를 함께 씀)

const SIZE = 15;
const CELL = 34;
const PAD = 28;
const EXTRA_X = 22;    // 가로 방향 여백 추가분 (좌우 각각)
const EXTRA_BOTTOM = 64; // 세로 방향 하단 여백 추가분 (알까기 당기는 선 공간 확보)
const GRID_SPAN = CELL * (SIZE - 1);
const GRID_OFFSET_X = PAD + EXTRA_X; // 격자가 캔버스 안에서 시작하는 x좌표
const DIM_W = PAD * 2 + GRID_SPAN + EXTRA_X * 2;
const DIM_H = PAD * 2 + GRID_SPAN + EXTRA_BOTTOM;
const INTERVAL = 3;   // 자신의 돌을 N개 놓을 때마다 카드 1장 획득
const HAND_LIMIT = 4;
const EMPTY = 0, BLACK = 1, WHITE = 2;
const WALL = 3; // 장벽: 누구의 돌도 아닌 칸 (둘 수 없고 줄도 끊음)
const R = CELL * 0.42; // 돌 반지름

const CARD_POOL = [
  { id: 'chain', name: '연속 착수', icon: '⚡', desc: '이번 턴에 총 3번까지 착수할 수 있습니다 (단, 이번 턴에 이미 둔 자리 포함 2칸 이내에는 놓을 수 없음).', type: 'chain_move', weight: 10 },
  { id: 'windmill', name: '풍차', icon: '🎡', desc: '내 돌 1개를 풍차로 만듭니다. 주변 8칸은 상대가 둘 수 없습니다.', type: 'windmill', weight: 10 },
  { id: 'sixsense', name: '식스센스', icon: '👁️', desc: '승리 조건이 5목에서 6목으로 영구히 바뀝니다.', type: 'six_sense', weight: 8 },
  { id: 'trade', name: '맞교환', icon: '🔄', desc: '상하좌우로 맞닿은 흑돌과 백돌 한 쌍을 골라 서로 색을 바꿉니다. 오목/육목이 완성되는 교환은 할 수 없으며, 사용 즉시 내 턴이 종료됩니다.', type: 'trade', weight: 10 },
  { id: 'bomb', name: '폭파', icon: '💥', desc: '상대 돌 1개를 제거합니다. 터진 자리는 폭파 구멍이 되어 2턴 동안 아무도 둘 수 없습니다.', type: 'remove_enemy', weight: 5 },
  { id: 'reversal', name: '전세 역전', icon: '☯️', desc: '보드의 모든 흑돌과 백돌을 통째로 뒤바꿉니다. 사용 즉시 내 턴이 종료됩니다. (가장 희귀)', type: 'reversal', weight: 2 },
  { id: 'alkkagi', name: '알까기 모드', icon: '🪀', desc: '흑, 백 순서로 한 번씩 알까기로 새 돌을 발사합니다. 흩어진 돌은 가장 가까운 자리로 고정됩니다.', type: 'alkkagi', weight: 8 },
  { id: 'teleport', name: '순간이동', icon: '✨', desc: '내 돌 1개를 무작위 빈 칸으로 이동시킵니다.', type: 'teleport', weight: 12 },
  { id: 'earthquake', name: '지진', icon: '🫨', desc: '보드의 모든 돌이 각자 주변의 무작위 빈 칸으로 흔들려 이동합니다.', type: 'earthquake', weight: 8 },
  { id: 'blockade', name: '봉쇄', icon: '🚫', desc: '상대가 다음에 사용하는 카드 1장을 무효화합니다 (카드는 소모됨). (희귀 카드)', type: 'blockade', weight: 3 },
  { id: 'trap', name: '함정', icon: '🪤', desc: '빈 칸에 함정을 설치합니다. 상대가 그 칸에 두면 돌이 사라지고 나는 카드를 얻습니다. 설치했다는 사실만 상대에게 알려지고, 위치는 나에게만 보입니다.', type: 'trap', weight: 10 },
  { id: 'shield', name: '보호막', icon: '🛡️', desc: '내 돌 하나를 고르면 그 돌 주변 3×3 안의 내 돌이 상대의 다음 2턴 동안 폭파·맞교환·감염·운석·전세 역전에서 보호됩니다.', type: 'shield', weight: 7 },
  { id: 'wall', name: '장벽', icon: '🧱', desc: '빈 칸 하나에 누구의 돌도 아닌 장벽을 세웁니다. 아무도 둘 수 없고 줄도 끊깁니다 (영구).', type: 'wall', weight: 7 },
  { id: 'meteor', name: '운석', icon: '☄️', desc: '판 위의 무작위 돌 1개가 무작위 빈 칸으로 날아갑니다. 내 돌일 수도 있어요! (보호막 안의 돌은 안전)', type: 'meteor', weight: 5 },
  { id: 'infection', name: '감염', icon: '🦠', desc: '내 돌과 상하좌우로 맞닿은 상대 돌 중 무작위 2개를 내 돌로 전향시킵니다. 오목/육목이 완성되는 돌은 제외되며, 사용 즉시 내 턴이 종료됩니다.', type: 'infection', weight: 8 },
];

// 패에 들어간 카드에 표시할 짧은 설명 (전체 설명은 마우스를 올리면 툴팁으로 표시)
const CARD_SHORT_DESC = {
  chain: '이번 턴 3번 착수',
  windmill: '내 돌 주변 8칸 봉쇄',
  sixsense: '승리 조건 6목으로',
  trade: '맞닿은 흑·백 돌 색 교환 (턴 종료)',
  bomb: '상대 돌 1개 제거 (2턴간 그 자리 착수 금지)',
  reversal: '모든 돌 색 반전 (턴 종료)',
  alkkagi: '알까기로 새 돌 발사',
  teleport: '내 돌 1개 무작위 이동',
  earthquake: '모든 돌 주변으로 흔들기',
  blockade: '상대 다음 카드 무효화',
  trap: '빈 칸에 함정 설치',
  infection: '맞닿은 상대 돌 2개 전향 (턴 종료)',
  shield: '내 돌 주변 3×3 보호 (상대 2턴)',
  wall: '빈 칸에 영구 장벽',
  meteor: '무작위 돌 1개를 무작위 칸으로 (내 돌일 수도)',
};

// ================= 다국어 (한국어 기본 / English) =================
const CARD_EN = {
  chain: { name: 'Chain Move', desc: 'Place up to 3 stones this turn (not within 2 cells of any stone you already placed this turn).', short: '3 stones this turn' },
  windmill: { name: 'Windmill', desc: 'Turn one of your stones into a windmill. Your opponent cannot play on the 8 cells around it.', short: 'Block 8 cells around a stone' },
  sixsense: { name: 'Sixth Sense', desc: 'The win condition permanently changes from 5 to 6 in a row.', short: '6 in a row to win' },
  trade: { name: 'Swap', desc: "Pick a black and a white stone touching up/down/left/right and swap their colors. A swap can't complete a winning line. Your turn ends immediately.", short: 'Swap touching B/W stones (turn ends)' },
  bomb: { name: 'Bomb', desc: "Remove one of your opponent's stones. The blast leaves a crater that nobody can play on for 2 turns.", short: 'Remove 1 enemy stone (crater for 2 turns)' },
  reversal: { name: 'Reversal', desc: 'Swap the colors of every black and white stone on the board. Your turn ends immediately.', short: 'Flip every stone (turn ends)' },
  alkkagi: { name: 'Flick Mode', desc: 'Black, then White, each flick a new stone onto the board. Scattered stones snap to the nearest point.', short: 'Flick a new stone in' },
  teleport: { name: 'Teleport', desc: 'Move one of your stones to a random empty cell.', short: 'Move 1 stone at random' },
  earthquake: { name: 'Earthquake', desc: 'Every stone on the board shakes into a random nearby empty cell.', short: 'Shake every stone' },
  blockade: { name: 'Blockade', desc: 'Nullify the next card your opponent uses (the card is still spent).', short: "Nullify opponent's next card" },
  trap: { name: 'Trap', desc: 'Set a trap on an empty cell. If your opponent plays there, their stone vanishes and you get a card. Your opponent is told a trap was set, but only you can see where.', short: 'Set a trap on an empty cell' },
  shield: { name: 'Shield', desc: "Pick one of your stones: your stones in the 3×3 around it are protected from Bomb, Swap, Infection, Meteor and Reversal for your opponent's next 2 turns.", short: 'Protect a 3×3 area (2 enemy turns)' },
  wall: { name: 'Wall', desc: 'Build a neutral wall on an empty cell. Nobody can play there and it breaks lines (permanent).', short: 'Permanent wall on an empty cell' },
  meteor: { name: 'Meteor', desc: 'A random stone on the board is flung to a random empty cell — it could be yours! (Shielded stones are safe.)', short: 'Fling a random stone (maybe yours)' },
  infection: { name: 'Infection', desc: 'Convert 2 random enemy stones touching yours (up/down/left/right) to your color. Stones that would complete a winning line are skipped. Your turn ends immediately.', short: 'Convert 2 touching enemies (turn ends)' },
};

// ================= 전설 카드: 게임 시작 때 한 번만 고르고(이후 카드 뽑기에는 안 나옴), 조건을 채우면 사용하거나 자동 발동 =================
// 패와 따로 '전설' 칸에 놓이며 판마다 1번. 양쪽 모두 서로의 전설 카드와 진행 상황을 볼 수 있음
const LEGEND_POOL = [
  { id: 'obelisk', icon: '🗿', name: '오목의 거신병', short: '내 돌 3개 희생 → 상대 돌이 가장 많은 줄 분쇄',
    desc: '내 돌 3개를 골라 희생하면, 상대 돌이 가장 많은 한 줄(가로·세로·대각선)의 상대 돌을 모두 부숩니다. 보호받는 돌은 남습니다. 조건: 내 돌 3개 이상.' },
  { id: 'nothing', icon: '🧘', name: '무소유', auto: true, short: '패 0장 3턴 연속 → 상대 패 전부 버리기',
    desc: '내 턴을 패 0장으로 마치기를 3턴 연속 하면(그 턴에 새로 고른 카드는 빼고 셈), 상대가 카드를 쥐고 있을 때 자동 발동: 상대는 패를 모두 버리고 나는 그 장수만큼 카드를 받습니다.' },
  { id: 'latebloom', icon: '🐌', name: '대기만성', short: '40수 이후 → 이번 턴 5번 착수',
    desc: '판에 둔 수가 모두 40수 이상이면 사용 가능. 이번 턴에 거리 제한 없이 5번 착수합니다. 단, 이번 턴의 착수로는 승리 줄을 완성할 수 없습니다.' },
  { id: 'blind', icon: '🙈', name: '눈 감고 두기', short: '멀리 3번 두기 → 풍차·함정 무시 + 영구 보호 돌',
    desc: '내 최근 3번의 착수가 모두 상대 돌과 3칸 이상 떨어져 있었으면 사용 가능. 이번 턴의 다음 착수는 풍차·함정을 무시하고, 그 돌은 영원히 폭파·감염·맞교환·운석·전세 역전에 당하지 않습니다.' },
  { id: 'clown', icon: '🤡', name: '광대의 한 수', short: '내 돌 3개 이상 잃음 → 모두 제자리로 귀환',
    desc: '폭파·함정·감염·맞교환·전설 카드 등으로 내 돌을 3개 이상 잃었으면 사용 가능. 사라진 돌이 모두 제자리로 돌아오고, 그 자리의 상대 돌은 가까운 빈 칸으로 밀려납니다. (승리 줄이 완성되는 자리, 보호받는 상대 돌 자리는 제외)' },
  { id: 'chicken', icon: '🍗', name: '치킨 게임', short: '둘 다 3줄 이상 → 동전 던져 한쪽 줄 삭제',
    desc: '양쪽 모두 3개 이상 이어진 줄이 있으면 사용 가능. 동전을 던져 진 쪽의 가장 긴 줄이 사라집니다. 내 줄일 수도 있어요! (보호받는 돌은 남음)' },
  { id: 'sloth', icon: '🦥', name: '나무늘보', auto: true, short: '카드 없이 가장자리만 5턴 → 가장자리 돌 전진',
    desc: '카드를 쓰지 않고 가장자리 두 줄에만 두는 턴을 5턴 연속 하면 자동 발동: 가장자리 두 줄에 있는 내 돌이 모두 중앙 쪽으로 한 칸씩 이동합니다. (승리 줄이 완성되는 이동은 제외)' },
  { id: 'mirror', icon: '🪞', name: '따라쟁이', short: '좌우 대칭 3번 → 상대가 마지막으로 쓴 카드 복사',
    desc: '상대가 방금 둔 자리의 좌우 대칭 자리에 3번 두면 사용 가능. 상대가 마지막으로 쓴 카드를 복사해 바로 사용합니다 (이번 턴의 카드 사용으로 셈).' },
  { id: 'nap', icon: '💤', name: '낮잠', auto: true, mpOnly: true, short: '내 턴에 10초 가만히 → 2번 착수 + 상대 카드 무효',
    desc: '멀티플레이 전용. 내 턴에 10초 동안 아무것도 안 하면 자동 발동: 이번 턴에 2번 착수하고, 상대가 다음에 쓰는 카드 1장은 무효가 됩니다.' },
  { id: 'allin', icon: '🎰', name: '올인', short: '패 4장 전부 버림 → 동전: 상대 돌 절반 or 내 돌 절반',
    desc: '패가 4장으로 꽉 찼을 때 사용 가능. 패를 모두 버리고 동전을 던집니다. 이기면 상대 돌의 절반, 지면 내 돌의 절반이 무작위로 사라집니다. (보호받는 돌은 남음)' },
  { id: 'turtle', icon: '🐢', name: '토끼와 거북이', short: '돌이 5개 이상 적음 → 나만 4목으로도 승리',
    desc: '판 위의 내 돌이 상대보다 5개 이상 적으면 사용 가능. 이후 나는 정확히 4개를 이어도 승리합니다. 사용 즉시 턴이 끝납니다.' },
  { id: 'king', icon: '👑', name: '왕의 귀환', short: '첫 돌 생존 + 20수 → 주변 8칸을 내 돌로',
    desc: '내가 처음 둔 돌이 아직 그 자리에 있고 판에 둔 수가 20수 이상이면 사용 가능. 그 돌 주변 8칸의 빈 칸이 모두 내 돌로 채워집니다. (승리 줄이 완성되는 칸은 제외)' },
];
LEGEND_POOL.forEach(c => { c.legend = true; c.type = 'legend'; });
const LEGEND_EN = {
  obelisk: { name: 'Gomoku Colossus', short: 'Sacrifice 3 stones → smash the most crowded enemy line',
    desc: 'Sacrifice 3 of your stones to smash every enemy stone on the single line (row, column or diagonal) holding the most enemy stones. Protected stones survive. Needs 3+ stones of yours.' },
  nothing: { name: 'Nothing Owned', short: 'Empty hand 3 turns → opponent discards their hand',
    desc: 'End 3 turns in a row with an empty hand (a card you just picked that turn does not count). It then triggers while your opponent holds cards: they discard their whole hand and you draw that many.' },
  latebloom: { name: 'Late Bloomer', short: 'After 40 moves → 5 placements this turn',
    desc: 'Usable once 40+ moves have been played. Place 5 stones this turn with no distance limit, but none of them may complete a winning line.' },
  blind: { name: 'Blindfolded', short: '3 far moves → ignore windmills/traps + protected stone',
    desc: 'Usable when each of your last 3 stones was placed 3+ cells away from every enemy stone. Your next stone this turn ignores windmills and traps, and is forever immune to Bomb, Infection, Swap, Meteor and Reversal.' },
  clown: { name: "Clown's Gambit", short: 'Lost 3+ stones → they all come back',
    desc: 'Usable once you have lost 3+ stones (Bomb, Trap, Infection, Swap, Legends…). All of them return to their spots, pushing any enemy stone there to a nearby empty cell. (Spots that would complete a winning line or hold a protected enemy stone are skipped.)' },
  chicken: { name: 'Chicken Game', short: 'Both have a 3-line → coin flip erases one side',
    desc: "Usable when both sides have a line of 3+. Flip a coin: the loser's longest line vanishes — it might be yours! (Protected stones survive.)" },
  sloth: { name: 'Sloth', short: '5 card-free edge turns → edge stones creep inward',
    desc: 'Play 5 turns in a row using no cards and placing only on the outer two rows. It then triggers: all your stones on the outer two rows move one step toward the center. (Moves that would complete a winning line are skipped.)' },
  mirror: { name: 'Copycat', short: '3 mirrored moves → copy their last card',
    desc: "Place 3 times on the left-right mirror of your opponent's last move. Then copy the card your opponent used last and use it right away (counts as this turn's card)." },
  nap: { name: 'Nap', short: 'Idle 10s on your turn → 2 placements + nullify their card',
    desc: "Multiplayer only. Do nothing for 10 seconds on your turn and it triggers: you place 2 stones this turn and your opponent's next card is nullified." },
  allin: { name: 'All-in', short: 'Discard a full hand → coin flip: half their stones or half yours',
    desc: "Usable with a full hand of 4. Discard it all and flip a coin: win and half of the enemy stones vanish, lose and half of yours do. (Protected stones survive.)" },
  turtle: { name: 'Tortoise and Hare', short: '5+ fewer stones → you alone win with 4',
    desc: 'Usable when you have 5+ fewer stones on the board than your opponent. From then on, exactly 4 in a row also wins for you. Your turn ends immediately.' },
  king: { name: 'Return of the King', short: 'First stone alive + 20 moves → fill its 8 neighbors',
    desc: 'Usable when your very first stone is still in place and 20+ moves have been played. Every empty cell around it becomes your stone. (Cells that would complete a winning line are skipped.)' },
};
function findAnyCard(id) { return CARD_POOL.find(c => c.id === id) || LEGEND_POOL.find(c => c.id === id) || null; }

const I18N = {
  ko: {
    'title': '증강 오목',
    'sub': '3수마다 카드 1장 · 턴마다 카드 1장 사용',
    'lang.toggle': 'English', 'lang.aria': '언어 바꾸기',
    'settings': '설정', 'settings.reduceMotion': '움직임 줄이기',
    'settings.reduceMotion.desc': '카드 발동 연출을 움직임 없는 페이드로 바꾸고, 파티클과 판 흔들림을 끕니다.',
    'fx.who': '{color} — 카드 발동', 'log.oppCard': '{color}: {icon} {card} 발동',
    'mode.local': '로컬 모드', 'mode.local.desc': '한 기기에서 둘이',
    'mode.bot': '봇전', 'mode.bot.desc': 'AI와 대결 ({n})', 'bot.level': '봇 난이도',
    'mode.mp': '멀티플레이', 'mode.mp.desc': '온라인 대결',
    'mode.tut': '튜토리얼', 'mode.tut.desc': '1분 만에 규칙 익히기',
    'tut.1': '① 같은 색 5개를 한 줄로 놓으면 승리! 빈 칸을 눌러 흑 5개를 완성하세요.',
    'tut.2': '② 백이 양쪽이 열린 4! 돌 하나로는 못 막아요. 아래 패의 🧱 장벽 카드로 한쪽을 막고, 돌로 다른 쪽을 막으세요.',
    'tut.2.retry': '아직 백이 이길 수 있어요. 다시 해 봐요!',
    'tut.3': '③ 끝! 3수마다 카드 1장을 고르고, 턴마다 1장 쓸 수 있어요. 카드는 패에서 눌러 쓰면 됩니다.',
    'tut.play': '봇전 시작',
    'back': '← 메뉴로', 'first': '선공', 'first.random': '🎲 랜덤', 'first.me': '내가 먼저', 'first.opp': '상대 먼저',
    'room.create': '새 방 만들기', 'or': '또는', 'room.code': '방 코드 입력', 'room.join': '코드로 참가하기', 'room.codeLabel': '방 코드 (상대에게 알려 주세요)',
    'cancel': '취소', 'ok': '확인', 'next.card': '다음 카드까지',
    'draft.title': '{color} — 카드 획득', 'draft.sub': '한 장을 골라 패에 넣으세요', 'rare': '희귀',
    'undo': '한 수 무르기', 'reset': '새 게임', 'hand.black': '흑 패', 'hand.white': '백 패',
    'hand.none': '없음', 'hand.hidden': '비공개',
    'cd.use': '사용하기', 'cd.close': '닫기',
    'cd.notTurn': '내 차례에만 쓸 수 있어요', 'cd.used': '이번 턴에 이미 카드를 썼어요 (턴당 1장)', 'cd.busy': '지금은 쓸 수 없어요',
    'cd.opp': '상대의 카드예요',
    'log.title': '기록', 'log.empty': '아직 기록이 없습니다',
    'chat.title': '채팅', 'chat.ph': '메시지 입력', 'chat.aria': '채팅 메시지', 'chat.send': '전송',
    'chat.empty': '아직 메시지가 없습니다', 'chat.error': '채팅 서버에 연결할 수 없습니다', 'chat.me': '나', 'chat.opp': '상대',
    'chat.sendFail': '💬 메시지를 보내지 못했습니다',
    'black': '흑', 'white': '백',
    'status.turn': '{color} 차례', 'status.mine': ' (내 차례)', 'status.opp': ' (상대 차례)',
    'status.alkOther': '{color}이(가) 알까기 중입니다...', 'alk.running': '알까기 진행 중...',
    'alk.prompt': '{color} 알까기 · 아래 돌을 당겨 발사', 'rule.len': '{n}목 규칙',
    'confirm.card': '{card} 사용할까요?', 'confirm.target': '이 대상을 선택할까요?', 'confirm.place': '이 위치에 착수할까요?',
    'banner.win': '{color} 승리', 'banner.draw': '무승부', 'banner.left': '{color}이(가) 게임을 나갔습니다',
    'banner.suffix': ' — 새 게임을 눌러 다시 시작하세요',
    'banner.suffixLoser': ' — 선공/후공을 골라 재대결하세요', 'banner.suffixWinner': ' — 상대가 선공/후공을 고르는 중',
    'rematch.loser': '졌습니다. 재대결에서 선공/후공을 고르세요', 'rematch.winner': '진 쪽이 선공/후공을 고르는 중입니다...',
    'rematch.first': '선공(흑)으로', 'rematch.second': '후공(백)으로',
    'notice.rematchFirst': '🔁 재대결 — 진 쪽이 선공(흑)을 골랐습니다', 'notice.rematchSecond': '🔁 재대결 — 진 쪽이 후공(백)을 골랐습니다',
    'rematch.random': '🎲 랜덤', 'notice.rematchRandom': '🔁 재대결 — 선후공을 랜덤으로 정했습니다', 'log.youAre': '🎯 이번 판: 나는 {color}',
    'menu.mpFail': '멀티플레이 서버 연결에 실패했습니다. 잠시 후 다시 열어주세요.',
    'lobby.connErr': '연결 오류가 발생했습니다. 새로고침 후 다시 시도해주세요.',
    'lobby.connecting': '서버에 연결하는 중입니다. 잠시 후 다시 눌러주세요.',
    'lobby.creating': '방을 만드는 중...',
    'lobby.waitingFirst': '상대를 기다리는 중... (나: 흑, 선공)',
    'lobby.waitingSecond': '상대를 기다리는 중... (나: 백, 후공)',
    'lobby.enterCode': '코드를 입력하세요', 'lobby.joining': '입장하는 중...', 'lobby.notFound': '방을 찾을 수 없습니다',
    'lobby.full': '이미 인원이 찼습니다', 'lobby.reconnected': '다시 접속했습니다.', 'lobby.joinFail': '참가에 실패했습니다. 코드를 확인해주세요.',
    'bot.log': '🤖 봇 난이도 {n}',
    'bot.hint.1': '입문 · 실수 많음',
    'bot.hint.3': '초급',
    'bot.hint.5': '중급 · 카드 활용',
    'bot.hint.7': '고급 · 2수 앞',
    'bot.hint.10': '최상급 · 4수 앞',
    'bot.hint.20': '얼티밋 · 깊이 읽음',
    'bot.ultimate': '얼티밋', 'bot.thinking': '🤖 봇이 생각 중...',
    'bot.super': '슈퍼 울트라 짱짱맨', 'bot.hint.50': '최강 · 카드까지 계산',
    'side.title': '선공/후공 선택', 'side.sub': '흑이 먼저 둡니다', 'side.first': '선공 (흑)', 'side.second': '후공 (백)', 'side.random': '랜덤',
    'side.prompt': '선공/후공을 고르세요', 'log.sideFirst': '🤖 봇전 — 내가 선공(흑)', 'log.sideSecond': '🤖 봇전 — 내가 후공(백)',
    'tgt.windmill': '풍차로 만들 내 돌을 클릭하세요', 'tgt.selfRemove': '제거할 내 돌을 클릭하세요',
    'tgt.remove': '제거할 상대 돌을 클릭하세요', 'tgt.trade1': '교환할 돌 하나를 클릭하세요 (반대 색 돌과 맞닿은 돌)',
    'tgt.trade2': '맞닿은 반대 색 돌을 클릭하세요', 'tgt.teleport': '이동시킬 내 돌을 클릭하세요', 'tgt.trap': '함정을 설치할 빈 칸을 클릭하세요',
    'log.windmillBlocked': '🎡 풍차 주변이라 둘 수 없는 칸입니다',
    'log.chainTooClose': '⚡ 연속 착수 — 이번 턴에 이미 둔 자리(포함) 2칸 이내에는 놓을 수 없습니다',
    'log.trapHit': '🪤 함정 발동! {color}의 돌이 사라졌습니다',
    'log.skipTurn': '{color}: ⏭️ 이번 턴을 건너뜁니다',
    'log.handOverflow': '{color}: 패 한도 초과로 {card} 소멸',
    'log.cardGained': '{color}: {icon} {card} 획득', 'log.cardGainedHand': '{color}: {icon} {card} 획득 (패에 저장)',
    'log.blockadeHit': '{color}: 🚫 봉쇄 — {icon} {card} 카드가 무효화되었습니다',
    'notice.blockadeHit': '🚫 봉쇄로 {color}의 카드 1장이 무효화되었습니다',
    'log.chainUsed': '{color}: {icon} 연속 착수 발동 — 이번 턴 총 3착',
    'log.sixAlready': '{color}: 이미 6목 규칙이 적용 중입니다', 'log.sixUsed': '{color}: {icon} 식스센스 발동 — 이제부터 6목',
    'log.reversalUsed': '{color}: {icon} 전세 역전 발동 — 모든 돌 색 반전 (턴 종료)',
    'log.noWindmillTarget': '{color}: 풍차로 만들 수 있는 내 돌 없음', 'log.noOwnStoneRemove': '{color}: 제거할 내 돌 없음',
    'log.noTarget': '{color}: 제거할 대상 없음', 'log.noTradePair': '{color}: 맞닿은 흑·백 돌이 없어 교환할 수 없음',
    'log.alkUsed': '{color}: {icon} 알까기 모드 발동', 'log.noOwnStoneMove': '{color}: 이동시킬 내 돌 없음',
    'log.noEmptyMove': '{color}: 이동할 빈 칸 없음', 'log.quakeUsed': '{color}: {icon} 지진 발동 — 모든 돌이 흔들려 재배치됨',
    'log.blockadeUsed': '{color}: {icon} 봉쇄 발동 — 상대가 다음에 쓰는 카드는 무효가 됩니다',
    'notice.blockadeUsed': '🚫 {color}이(가) 봉쇄를 사용했습니다 — 상대의 다음 카드가 무효화됩니다',
    'log.noEmptyTrap': '{color}: 함정을 설치할 빈 칸 없음', 'log.noInfectTarget': '{color}: 감염시킬 인접 상대 돌 없음',
    'log.noSafeInfect': '{color}: 감염할 수 있는 안전한 대상 없음 (오목/육목 완성 방지)',
    'log.infectUsed': '{color}: {icon} 감염 발동 — 상대 돌 {n}개 전향 (턴 종료)',
    'log.bombDone': '{color}: 💥 상대 돌 제거 — 그 자리는 2턴 동안 착수 금지', 'log.craterBlocked': '💥 폭파 구멍이라 아직 둘 수 없는 칸입니다', 'log.selfRemove': '{color}: 🫳 내 돌 회수',
    'log.noEmptyCell': '이동할 빈 칸이 없습니다', 'log.teleportDone': '{color}: ✨ 순간이동 발동',
    'log.trapExists': '이미 함정이 있는 칸입니다. 다른 칸을 클릭하세요',
    'log.trapSet': '⚠️ {color}이(가) 함정을 설치했습니다! 상대는 조심하세요', 'notice.trapSet': '⚠️ 상대가 함정을 설치했습니다! 조심하세요',
    'log.windmillExists': '이미 풍차인 돌입니다. 다른 돌을 클릭하세요', 'log.windmillSet': '{color}: 🎡 풍차 설치',
    'log.tradeNoLine': '🔄 오목/육목이 완성되는 맞교환은 할 수 없습니다. 다른 쌍을 고르세요',
    'log.tradeNoNeighbor': '맞닿은 반대 색 돌이 없는 돌입니다. 다른 돌을 고르세요', 'log.tradeDone': '{color}: 🔄 맞교환 발동 (턴 종료)',
    'log.alkEnd': '🪀 알까기 종료 — 오목판으로 복귀', 'log.alkTurn': '{color}: 알까기 차례',
    'log.trapHitOpp': '🪤 함정 발동! 상대 돌이 사라졌습니다', 'log.trapStopWin': '🪤 함정이 승리를 막았습니다 — 게임을 계속합니다',
    'notice.trapFired': '🪤 함정이 발동되어 상대 돌이 제거됐습니다',
    'tgt.shield': '보호막을 칠 내 돌을 클릭하세요 (주변 3×3)', 'tgt.wall': '장벽을 세울 빈 칸을 클릭하세요',
    'log.shieldUsed': '{color}: 🛡️ 보호막 발동 — 주변 3×3의 돌이 상대 2턴 동안 보호됨', 'log.shielded': '🛡️ 보호막으로 보호된 돌입니다. 다른 대상을 고르세요',
    'log.noShieldTarget': '{color}: 보호할 내 돌 없음',
    'log.stealUsed': '{color}: 🃏 강탈 발동', 'log.stealGot': '{color}: 🃏 상대에게서 {card} 카드를 빼앗음', 'log.stealEmpty': '{color}: 🃏 강탈 — 상대 패가 비어 있음',
    'log.stealLost': '🃏 상대가 내 {card} 카드를 빼앗아 갔습니다',
    'log.wallUsed': '{color}: 🧱 장벽 설치', 'log.wallNeedEmpty': '빈 칸에만 장벽을 세울 수 있습니다',
    'log.meteorUsed': '{color}: ☄️ 운석 발동 — {color2}의 돌이 날아감', 'log.meteorNone': '{color}: 운석이 떨어질 돌이 없음',
    // 전설 카드
    'lg.draftTitle': '{color} — 전설 카드 선택', 'lg.draftSub': '게임 시작 때 한 번만! 조건을 채우면 판을 뒤집는 카드 1장을 고르세요',
    'lg.badge': '전설', 'lg.auto': '자동 발동', 'lg.manual': '조건 충족 시 사용',
    'lg.picked': '{color}: 전설 카드 {icon} {card} 선택', 'lg.used': '{color}: {icon} {card} 발동!',
    'lg.done': '사용함', 'lg.ready': '사용 가능!', 'lg.notReady': '아직 조건이 채워지지 않았어요',
    'lg.cdProg': '진행: {p}', 'lg.cdAutoNote': '조건을 채우면 자동으로 발동돼요',
    'lg.p.obelisk': '내 돌 {n}/3', 'lg.p.nothing': '빈 손 {n}/3턴', 'lg.p.latebloom': '{n}/40수', 'lg.p.blind': '멀리 두기 {n}/3',
    'lg.p.clown': '잃은 돌 {n}/3', 'lg.p.chicken': '긴 줄 나 {a} · 상대 {b} (둘 다 3 이상)', 'lg.p.sloth': '가장자리 {n}/5턴',
    'lg.p.mirror': '대칭 {n}/3', 'lg.p.mirrorCard': '대칭 {n}/3 · 복사할 카드 {card}', 'lg.p.nap': '내 턴에 10초 가만히',
    'lg.p.allin': '패 {n}/4', 'lg.p.turtle': '돌 차이 {n}/5', 'lg.p.king': '{n}/20수 · 첫 돌 {s}', 'lg.alive': '살아 있음', 'lg.dead': '사라짐',
    'tgt.obelisk': '희생할 내 돌 3개를 고르세요 ({n}/3)',
    'lg.obeliskDone': '{color}: 🗿 거신병이 상대 돌 {n}개가 있던 줄을 분쇄!', 'lg.obeliskNone': '{color}: 🗿 부술 상대 돌이 없음',
    'lg.nothingDone': '{color}: 🧘 무소유 — 상대가 패 {n}장을 모두 버리고, 그만큼 카드를 받음', 'lg.nothingLost': '🧘 상대의 무소유! 내 패 {n}장을 모두 버림',
    'lg.bigOn': '{color}: 🐌 대기만성 — 이번 턴 5번 착수 (오목 완성 불가)', 'lg.bigNoWin': '🐌 대기만성 턴에는 오목을 완성할 수 없어요',
    'lg.blindOn': '{color}: 🙈 눈 감고 두기 — 다음 착수는 풍차·함정 무시, 그 돌은 영구 보호',
    'lg.clownDone': '{color}: 🤡 광대의 한 수 — 사라졌던 돌 {n}개 귀환',
    'lg.chickenWin': '{color}: 🍗 치킨 게임 승리! 상대의 가장 긴 줄 {n}개가 사라짐', 'lg.chickenLose': '{color}: 🍗 치킨 게임 패배… 내 가장 긴 줄 {n}개가 사라짐',
    'lg.slothDone': '{color}: 🦥 나무늘보 — 가장자리 돌 {n}개가 중앙으로 한 칸씩',
    'lg.mirrorDone': '{color}: 🪞 따라쟁이 — 상대의 {card} 복사', 'lg.mirrorNone': '{color}: 🪞 복사할 상대 카드가 없음',
    'lg.napDone': '{color}: 💤 낮잠 — 이번 턴 2번 착수, 상대의 다음 카드는 무효',
    'lg.allinWin': '{color}: 🎰 올인 성공! 상대 돌 {n}개가 사라짐', 'lg.allinLose': '{color}: 🎰 올인 실패… 내 돌 {n}개가 사라짐',
    'lg.turtleDone': '{color}: 🐢 토끼와 거북이 — 이제 {color}는 4목으로도 승리 (턴 종료)', 'rule.turtle': '🐢 {color} 4목',
    'lg.kingDone': '{color}: 👑 왕의 귀환 — 첫 돌 주변에 돌 {n}개',
  },
  en: {
    'title': 'Gomoku-ARAM',
    'sub': 'A card every 3 stones · one card per turn',
    'lang.toggle': '한국어', 'lang.aria': 'Change language',
    'settings': 'Settings', 'settings.reduceMotion': 'Reduce motion',
    'settings.reduceMotion.desc': 'Card effects become a still fade, with no particles or board shake.',
    'fx.who': '{color} — Card activated', 'log.oppCard': '{color}: {icon} {card} activated',
    'mode.local': 'Local', 'mode.local.desc': 'Two players, one device',
    'mode.bot': 'vs Bot', 'mode.bot.desc': 'Play the AI ({n})', 'bot.level': 'Bot level',
    'mode.mp': 'Multiplayer', 'mode.mp.desc': 'Play online',
    'mode.tut': 'Tutorial', 'mode.tut.desc': 'Learn the rules in a minute',
    'tut.1': '① Five of your color in a row wins! Tap an empty cell to make five black.',
    'tut.2': "② White has an open four! One stone can't stop it. Use the 🧱 Wall card in your hand on one end, then place a stone on the other.",
    'tut.2.retry': 'White can still win. Try again!',
    'tut.3': "③ Done! You pick a card every 3 stones and can use one per turn — tap it in your hand.",
    'tut.play': 'Play the bot',
    'back': '← Menu', 'first': 'First move', 'first.random': '🎲 Random', 'first.me': 'Me first', 'first.opp': 'Opponent first',
    'room.create': 'Create room', 'or': 'or', 'room.code': 'Room code', 'room.join': 'Join with code', 'room.codeLabel': 'Room code (share it with your opponent)',
    'cancel': 'Cancel', 'ok': 'OK', 'next.card': 'Next card',
    'draft.title': '{color} — Pick a card', 'draft.sub': 'Choose one to add to your hand', 'rare': 'Rare',
    'undo': 'Undo', 'reset': 'New game', 'hand.black': "Black's hand", 'hand.white': "White's hand",
    'hand.none': 'None', 'hand.hidden': 'Hidden',
    'cd.use': 'Use', 'cd.close': 'Close',
    'cd.notTurn': 'You can only use it on your turn', 'cd.used': 'You already used a card this turn (1 per turn)', 'cd.busy': "Can't use it right now",
    'cd.opp': "This is your opponent's card",
    'log.title': 'Log', 'log.empty': 'Nothing yet',
    'chat.title': 'Chat', 'chat.ph': 'Type a message', 'chat.aria': 'Chat message', 'chat.send': 'Send',
    'chat.empty': 'No messages yet', 'chat.error': "Can't connect to chat", 'chat.me': 'Me', 'chat.opp': 'Opponent',
    'chat.sendFail': "💬 Couldn't send the message",
    'black': 'Black', 'white': 'White',
    'status.turn': "{color}'s turn", 'status.mine': ' (you)', 'status.opp': ' (opponent)',
    'status.alkOther': '{color} is flicking...', 'alk.running': 'Stones in motion...',
    'alk.prompt': '{color} flick · pull the bottom stone and release', 'rule.len': '{n} in a row',
    'confirm.card': 'Use {card}?', 'confirm.target': 'Select this target?', 'confirm.place': 'Place a stone here?',
    'banner.win': '{color} wins', 'banner.draw': 'Draw', 'banner.left': '{color} left the game',
    'banner.suffix': ' — press New game to play again',
    'banner.suffixLoser': ' — pick first or second for the rematch', 'banner.suffixWinner': ' — your opponent is picking first or second',
    'rematch.loser': 'You lost. Pick first or second for the rematch', 'rematch.winner': 'The loser is picking first or second...',
    'rematch.first': 'Go first (Black)', 'rematch.second': 'Go second (White)',
    'notice.rematchFirst': '🔁 Rematch — the loser chose to go first (Black)', 'notice.rematchSecond': '🔁 Rematch — the loser chose to go second (White)',
    'rematch.random': '🎲 Random', 'notice.rematchRandom': '🔁 Rematch — sides were picked at random', 'log.youAre': '🎯 This game: you are {color}',
    'menu.mpFail': "Couldn't reach the multiplayer server. Please reopen the page in a moment.",
    'lobby.connErr': 'Connection error. Please refresh and try again.',
    'lobby.connecting': 'Connecting to the server. Please try again in a moment.',
    'lobby.creating': 'Creating room...',
    'lobby.waitingFirst': 'Waiting for an opponent... (you: Black, first)',
    'lobby.waitingSecond': 'Waiting for an opponent... (you: White, second)',
    'lobby.enterCode': 'Enter a room code', 'lobby.joining': 'Joining...', 'lobby.notFound': 'Room not found',
    'lobby.full': 'This room is full', 'lobby.reconnected': 'Reconnected.', 'lobby.joinFail': 'Could not join. Please check the code.',
    'bot.log': '🤖 Bot level {n}',
    'bot.hint.1': 'Beginner · makes mistakes',
    'bot.hint.3': 'Novice',
    'bot.hint.5': 'Intermediate · uses cards',
    'bot.hint.7': 'Advanced · 2 moves ahead',
    'bot.hint.10': 'Master · 4 moves ahead',
    'bot.hint.20': 'Ultimate · deep reading',
    'bot.ultimate': 'Ultimate', 'bot.thinking': '🤖 Bot is thinking...',
    'bot.super': 'Super Ultra Awesome', 'bot.hint.50': 'Strongest · plans cards too',
    'side.title': 'Choose your side', 'side.sub': 'Black moves first', 'side.first': 'First (Black)', 'side.second': 'Second (White)', 'side.random': 'Random',
    'side.prompt': 'Choose first or second', 'log.sideFirst': '🤖 vs Bot — you play first (Black)', 'log.sideSecond': '🤖 vs Bot — you play second (White)',
    'tgt.windmill': 'Click one of your stones to make a windmill', 'tgt.selfRemove': 'Click one of your stones to remove',
    'tgt.remove': "Click an opponent's stone to remove", 'tgt.trade1': 'Click a stone to swap (one touching an opposite color)',
    'tgt.trade2': 'Now click the touching opposite stone', 'tgt.teleport': 'Click one of your stones to teleport', 'tgt.trap': 'Click an empty cell to set a trap',
    'log.windmillBlocked': "🎡 You can't play next to an enemy windmill",
    'log.chainTooClose': "⚡ Chain Move — can't place within 2 cells of stones placed this turn",
    'log.trapHit': "🪤 Trap sprung! {color}'s stone vanished",
    'log.skipTurn': '{color}: ⏭️ this turn is skipped',
    'log.handOverflow': '{color}: hand full — {card} discarded',
    'log.cardGained': '{color}: {icon} got {card}', 'log.cardGainedHand': '{color}: {icon} {card} added to hand',
    'log.blockadeHit': '{color}: 🚫 Blockade — {icon} {card} was nullified',
    'notice.blockadeHit': "🚫 Blockade nullified one of {color}'s cards",
    'log.chainUsed': '{color}: {icon} Chain Move — 3 stones this turn',
    'log.sixAlready': '{color}: 6 in a row is already in effect', 'log.sixUsed': '{color}: {icon} Sixth Sense — 6 in a row from now on',
    'log.reversalUsed': '{color}: {icon} Reversal — every stone flipped (turn ends)',
    'log.noWindmillTarget': '{color}: none of your stones can become a windmill', 'log.noOwnStoneRemove': '{color}: no stone of yours to remove',
    'log.noTarget': '{color}: nothing to remove', 'log.noTradePair': '{color}: no touching black/white pair to swap',
    'log.alkUsed': '{color}: {icon} Flick Mode!', 'log.noOwnStoneMove': '{color}: no stone of yours to move',
    'log.noEmptyMove': '{color}: no empty cell to move to', 'log.quakeUsed': '{color}: {icon} Earthquake — every stone got shaken around',
    'log.blockadeUsed': "{color}: {icon} Blockade — the opponent's next card will fail",
    'notice.blockadeUsed': "🚫 {color} used Blockade — the opponent's next card will be nullified",
    'log.noEmptyTrap': '{color}: no empty cell for a trap', 'log.noInfectTarget': '{color}: no touching enemy stone to infect',
    'log.noSafeInfect': '{color}: no safe target to infect (it would complete a line)',
    'log.infectUsed': '{color}: {icon} Infection — {n} enemy stone(s) converted (turn ends)',
    'log.bombDone': '{color}: 💥 removed an enemy stone — nobody can play there for 2 turns', 'log.craterBlocked': "💥 That cell is a bomb crater — you can't play there yet", 'log.selfRemove': '{color}: 🫳 took back a stone',
    'log.noEmptyCell': 'No empty cell to move to', 'log.teleportDone': '{color}: ✨ Teleport!',
    'log.trapExists': 'There is already a trap here. Pick another cell',
    'log.trapSet': '⚠️ {color} set a trap! Watch your step', 'notice.trapSet': '⚠️ Your opponent set a trap! Be careful',
    'log.windmillExists': 'That stone is already a windmill. Pick another', 'log.windmillSet': '{color}: 🎡 windmill built',
    'log.tradeNoLine': "🔄 A swap can't complete a winning line. Pick another pair",
    'log.tradeNoNeighbor': "That stone isn't touching an opposite color. Pick another", 'log.tradeDone': '{color}: 🔄 Swap! (turn ends)',
    'log.alkEnd': '🪀 Flick Mode over — back to the board', 'log.alkTurn': "{color}: flick turn",
    'log.trapHitOpp': "🪤 Trap sprung! The opponent's stone vanished", 'log.trapStopWin': '🪤 A trap stopped the win — the game goes on',
    'notice.trapFired': "🪤 A trap fired and removed the opponent's stone",
    'tgt.shield': 'Click one of your stones to shield (3×3 around it)', 'tgt.wall': 'Click an empty cell to build a wall',
    'log.shieldUsed': "{color}: 🛡️ Shield — stones in the 3×3 are protected for 2 enemy turns", 'log.shielded': '🛡️ That stone is shielded. Pick another target',
    'log.noShieldTarget': '{color}: no stone of yours to shield',
    'log.stealUsed': '{color}: 🃏 Steal!', 'log.stealGot': '{color}: 🃏 stole {card} from the opponent', 'log.stealEmpty': "{color}: 🃏 Steal — the opponent's hand is empty",
    'log.stealLost': '🃏 Your opponent stole your {card}',
    'log.wallUsed': '{color}: 🧱 wall built', 'log.wallNeedEmpty': 'A wall can only go on an empty cell',
    'log.meteorUsed': "{color}: ☄️ Meteor — a {color2} stone was flung away", 'log.meteorNone': '{color}: no stone for the meteor to hit',
    'lg.draftTitle': '{color} — Pick a Legend', 'lg.draftSub': 'Only once, at the start! Pick one game-changing card that unlocks when its condition is met',
    'lg.badge': 'Legend', 'lg.auto': 'Triggers automatically', 'lg.manual': 'Use once the condition is met',
    'lg.picked': '{color}: picked Legend {icon} {card}', 'lg.used': '{color}: {icon} {card} activated!',
    'lg.done': 'Used', 'lg.ready': 'Ready!', 'lg.notReady': "The condition isn't met yet",
    'lg.cdProg': 'Progress: {p}', 'lg.cdAutoNote': 'Triggers by itself once the condition is met',
    'lg.p.obelisk': 'Your stones {n}/3', 'lg.p.nothing': 'Empty hand {n}/3 turns', 'lg.p.latebloom': '{n}/40 moves', 'lg.p.blind': 'Far moves {n}/3',
    'lg.p.clown': 'Stones lost {n}/3', 'lg.p.chicken': 'Longest line you {a} · them {b} (both 3+)', 'lg.p.sloth': 'Edge turns {n}/5',
    'lg.p.mirror': 'Mirrors {n}/3', 'lg.p.mirrorCard': 'Mirrors {n}/3 · card to copy: {card}', 'lg.p.nap': 'Stay idle 10s on your turn',
    'lg.p.allin': 'Hand {n}/4', 'lg.p.turtle': 'Stone gap {n}/5', 'lg.p.king': '{n}/20 moves · first stone {s}', 'lg.alive': 'alive', 'lg.dead': 'gone',
    'tgt.obelisk': 'Pick 3 of your stones to sacrifice ({n}/3)',
    'lg.obeliskDone': '{color}: 🗿 The Colossus smashed a line holding {n} enemy stones!', 'lg.obeliskNone': '{color}: 🗿 no enemy stones to smash',
    'lg.nothingDone': '{color}: 🧘 Nothing Owned — the opponent discarded {n} card(s) and you drew as many', 'lg.nothingLost': "🧘 Opponent's Nothing Owned! You discarded all {n} card(s)",
    'lg.bigOn': '{color}: 🐌 Late Bloomer — 5 placements this turn (no winning line)', 'lg.bigNoWin': "🐌 You can't complete a winning line on a Late Bloomer turn",
    'lg.blindOn': '{color}: 🙈 Blindfolded — next stone ignores windmills and traps and is protected forever',
    'lg.clownDone': "{color}: 🤡 Clown's Gambit — {n} lost stone(s) returned",
    'lg.chickenWin': "{color}: 🍗 Chicken won! The opponent's longest line ({n}) vanished", 'lg.chickenLose': '{color}: 🍗 Chicken lost… your longest line ({n}) vanished',
    'lg.slothDone': '{color}: 🦥 Sloth — {n} edge stone(s) crept one step toward the center',
    'lg.mirrorDone': "{color}: 🪞 Copycat — copied the opponent's {card}", 'lg.mirrorNone': '{color}: 🪞 no opponent card to copy',
    'lg.napDone': "{color}: 💤 Nap — 2 placements this turn, the opponent's next card is nullified",
    'lg.allinWin': '{color}: 🎰 All-in won! {n} enemy stone(s) vanished', 'lg.allinLose': '{color}: 🎰 All-in lost… {n} of your stones vanished',
    'lg.turtleDone': '{color}: 🐢 Tortoise and Hare — {color} now also wins with 4 in a row (turn ends)', 'rule.turtle': '🐢 {color} 4 to win',
    'lg.kingDone': '{color}: 👑 Return of the King — {n} stone(s) around the first stone',
  },
};

let lang = 'ko';
try { if (localStorage.getItem('omok_lang') === 'en') lang = 'en'; } catch (e) {}

function colorName(c) { return c === BLACK ? t('black') : t('white'); }
function cardEn(id) { return CARD_EN[id] || LEGEND_EN[id]; }
function cardName(card) { const id = typeof card === 'string' ? card : card && card.id; const en = cardEn(id); return lang === 'en' && en ? en.name : (findAnyCard(id) || card || {}).name || ''; }
function cardDesc(card) {
  if (lang === 'en' && cardEn(card.id)) return cardEn(card.id).desc;
  return (findAnyCard(card.id) || card).desc;
}
function cardShort(card) {
  if (lang === 'en' && cardEn(card.id)) return cardEn(card.id).short;
  const lgc = LEGEND_POOL.find(c => c.id === card.id);
  return lgc ? lgc.short : (CARD_SHORT_DESC[card.id] || '');
}

// 키 + 매개변수로 문구 생성. {color}는 색 번호, {card}는 카드 id로 넘기면 현재 언어로 바뀜
function t(key, p) {
  const tpl = (I18N[lang] && I18N[lang][key]) || I18N.ko[key] || key;
  return tpl.replace(/\{(\w+)\}/g, (_, name) => {
    const v = p ? p[name] : undefined;
    if (name === 'color' || name === 'color2') return colorName(v);
    if (name === 'card') return cardName(v);
    return v === undefined || v === null ? '' : String(v);
  });
}
// 기록·알림은 {k, p} 형태로 저장해 두고 표시할 때 번역 (언어를 바꾸면 다시 번역됨, 상대와 언어가 달라도 각자 언어로 보임)
function L(k, p) { return p ? { k, p } : { k }; }
function fmt(msg) { return typeof msg === 'string' ? msg : (msg && msg.k ? t(msg.k, msg.p) : ''); }
